apiVersion: v1
kind: Service
metadata:
  name: vite-react-service
  namespace: spotify
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:730335218716:certificate/8f4eeeea-9a1d-443c-a8c8-4de7f8b19aec"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"  # SSL for port 443
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
  labels:
    app: vite-react
spec:
  selector:
    app: vite-react
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80  # Forward traffic to port 80 on the pods
  type: LoadBalancer
