# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Specify Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"  # Choose between internet-facing or internal
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:730335218716:certificate/8f4eeeea-9a1d-443c-a8c8-4de7f8b19aec"  # ACM Certificate ARN
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"  # Define the SSL ports
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"  # Backend protocol
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"  # Health check protocol for NLB
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "traffic-port"  # Use traffic-port for health check
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "20"  # Health check interval (in seconds)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"  # Health check timeout (in seconds)
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"  # Unhealthy threshold
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"  # Healthy threshold
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80  # Traffic will be forwarded to port 80 on your pods
  type: LoadBalancer
